print("Give me the first number: ", end="")
num1 = int(input())
print("Give me the second number: ", end="")
num2 = int(input())
print("Thank you!")
print(f"{num1} + {num2} = {num1 + num2}")
print(f"{num1} - {num2} = {num1 - num2}")
print(f"{num1} / {num2} = {(num1 / num2):.0f}")
print(f"{num1} * {num2} = {num1 * num2}")